resolver: lts-17.10

packages:
  - stellar-horizon
  - veche
  - yesod-auth-stellar

extra-deps:
  # veche
    - classy-prelude-yesod-1.5.0
  # stellar-horizon:exe
    - servant-cli-0.1.0.2
  # servant-cli; TODO update servant-cli deps
    - functor-combinators-0.4.1.0
    - nonempty-containers-0.3.4.4
    - trivial-constraint-0.7.0.0
